//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string employeeId { get; set; }
        public string managerId { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public string authorityId { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string address { get; set; }
        public string personalNumber { get; set; }
        public string name { get; set; }
        public string kataName { get; set; }
        public string telephoneNumber { get; set; }
        public string personalDocumentPath { get; set; }
        public string mailAddress { get; set; }
        public string customerId { get; set; }
        public string accountBankInfo { get; set; }
        public string avatarFilePath { get; set; }
        public Nullable<int> depentdentFamily { get; set; }
        public string entryDate { get; set; }
        public string leavingDate { get; set; }
        public string description { get; set; }
    }
}
