//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class paidholiday
    {
        public string paidHolidayId { get; set; }
        public string emplyeeId { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public string reason { get; set; }
        public string description { get; set; }
    }
}
